### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by danb35** [sipeed/NanoKVM#283]
HTTPS had been working just fine on my NanoKVM lite unit (it still works on my two units running 2.1.1), but stopped working with the update to, IIRC, 2.1.2, and it continues to not work under 2.1.5.  The interface is instead served over HTTP.  The server.yaml file is set properly:
```yaml
# cat /etc/kvm/server.yaml
protocol: https
port:
  http: 80 
  https: 443
cert:
  crt: /etc/ssl/certs/fullchain.pem
  key: /etc/ssl/private/privkey.pem
```
The cert and key files both exist, and they contain a valid Let's Encrypt cert and private key.  But nonetheless the interface is served over HTTP, not HTTPS.  What needs to change in order to effect this?
