### ISSUE TITLE
Video stream over reverse proxy

### ISSUE THREAD

**Issue by ajvcorreia** [sipeed/NanoKVM#374]
I have a nano kvm sitting behind an NGINX Proxy Manager reverse proxy.
The web interface comes up and all options are available but not the video signal.
Is there a special configuration I should be using in NGINX to allow the video signal to pass through?

**Comment by netandreus** [comment]
I don't know why, but when I opened the web ui in Chrome incognito mode I could see video output.

**Comment by szsong** [comment]
Have you tried swiching video mode from H264 to MJPEG? That solved the problem for me. but I have another issue, the HID are not working when I connect through reverse proxy, but works normally if I use local IP address to access..

**Comment by saucedge** [comment]
I'm having this issue

**Comment by kuroiookami77** [comment]
The same problem - NanoKVM behind Nginx Proxy. When accessing from an external network, there is no video in H264, but if switched to MJPEG, it works fine.

**Comment by dobrozhanskyi** [comment]
you need to configure TURN server for WebRTC,  you can see example in [doc](https://github.com/sipeed/NanoKVM/blob/main/server/README.md#configuration) 

```
# Address and authentication for custom TURN server
turn:
    turnAddr: example_addr
    turnUser: example_user
    turnCred: example_cred
```
